project:
  type: book
  output-dir: docs

book:
  title: "DS2023 Final_Project"
  author: "Ethan, Vinith, Alieen"
  favicon: logo.png
  description: "Patient 101's Recovery Journey: Data Driven Insights into Healthcare"
  keyword: data science, communicating, storytelling, data visualization
  url: https://junewayne.github.io/DS2023-Final-Project/ 
  sidebar:
    logo: logo.png
    search: true
  repo-url: https://github.com/JuneWayne/DS2023-Final-Project
  repo-branch: master
  image: logo.png



  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd

format:
  html:
    theme:
      light: minty
    code-fode: false
    backgroundcolor: '#FFFFFF'





